# Generated by Django 2.2.7 on 2020-09-25 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('guide_number', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('doctor_identifier', models.PositiveIntegerField(verbose_name='Código do Médico')),
                ('doctor_name', models.CharField(max_length=100, verbose_name='Nome do Médico')),
                ('query_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('query_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Consulta')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('exam_name', models.CharField(max_length=100, verbose_name='Nome do Exame')),
                ('exam_times', models.PositiveIntegerField(null=True, verbose_name='Número de Exames')),
                ('guide_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.MedicalExam', verbose_name='Número da Guia')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
            },
        ),
    ]
