# Generated by Django 2.2.7 on 2020-09-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200925_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='guide_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.MedicalExam', verbose_name='Número da Guia'),
        ),
    ]
